package util;

import entity.Estacao;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Persistence;
import jpa.EstacaoDao;

/**
 * Hello world!
 *
 */
public class App {
    private static Estacao estacao;
     public static void main(String[] args) throws IOException {
        
        List<String> nomeEstacoes = new ArrayList<String>();
        
        nomeEstacoes.add("Estação tubo Aeroporto Afonso Pena");
        nomeEstacoes.add("Estação tubo Agrárias");
        nomeEstacoes.add("Estação tubo Água Verde");
        nomeEstacoes.add("Estação tubo Ahú");
        nomeEstacoes.add("Estação tubo Alferes Poli (Catedral da Fé)");
        nomeEstacoes.add("Estação tubo Almirante Gonçalves");
        nomeEstacoes.add("Estação tubo Alto Boqueirão");
        nomeEstacoes.add("Estação tubo Antero de Quental");
        nomeEstacoes.add("Estação tubo Antônio Cavalheiros");
        nomeEstacoes.add("Estação tubo Antônio de Paula");
        nomeEstacoes.add("Estação tubo Antônio Lago");
        nomeEstacoes.add("Estação tubo Antônio Meirelles Sobrinho");
        nomeEstacoes.add("Estação tubo Araçá");
        nomeEstacoes.add("Estação tubo Arroio Cercado");
        nomeEstacoes.add("Estação tubo Assembleia");
        nomeEstacoes.add("Estação tubo Assembleia de Deus");
        nomeEstacoes.add("Estação tubo Autódromo");
        nomeEstacoes.add("Estação tubo Bairro Novo");
        nomeEstacoes.add("Estação tubo Barigui");
        nomeEstacoes.add("Estação tubo Bento Viana");
        nomeEstacoes.add("Estação tubo Bigorrilho");
        nomeEstacoes.add("Estação tubo Bom Jesus");
        nomeEstacoes.add("Estação tubo Brigadeiro Franco");
        nomeEstacoes.add("Estação tubo Bruno Filgueira");
        nomeEstacoes.add("Estação tubo Cajuru");
        nomeEstacoes.add("Estação tubo Camilo de Lellis");
        nomeEstacoes.add("Estação tubo Carlos Dietzsch");
        nomeEstacoes.add("Estação tubo Carlos Gomes");
        nomeEstacoes.add("Estação tubo Carlos Gomes");
        nomeEstacoes.add("Estação tubo Catedral da Fé");
        nomeEstacoes.add("Estação tubo Catulo da Paixão Cearense");
        nomeEstacoes.add("Estação tubo Cavalo Baio");
        nomeEstacoes.add("Estação tubo Central");
        nomeEstacoes.add("Estação tubo Centro Cívico (Assembleia)");
        nomeEstacoes.add("Estação tubo Centro Cívico (Palácio Iguaçu)");
        nomeEstacoes.add("Estação tubo Centro Médico Comunitário Bairro Novo");
        nomeEstacoes.add("Estação tubo Chapinhal");
        nomeEstacoes.add("Estação tubo China");
        nomeEstacoes.add("Estação tubo CIC Norte");
        nomeEstacoes.add("Estação tubo Círculo Militar");
        nomeEstacoes.add("Estação tubo Colégio Militar");
        nomeEstacoes.add("Estação tubo Comendador Fontana (Assembleia de Deus)");
        nomeEstacoes.add("Estação tubo Conselheiro Dantas");
        nomeEstacoes.add("Estação tubo Conselheiro Laurindo");
        nomeEstacoes.add("Estação tubo Constantino Marochi");
        nomeEstacoes.add("Estação tubo Coqueiros");
        nomeEstacoes.add("Estação tubo Coronel Dulcídio");
        nomeEstacoes.add("Estação tubo Coronel Luiz José");
        nomeEstacoes.add("Estação tubo dos Santos");
        nomeEstacoes.add("Estação tubo Del. Amazor Prestes");
        nomeEstacoes.add("Estação tubo Detran");
        nomeEstacoes.add("Estação tubo Dom Ático");
        nomeEstacoes.add("Estação tubo Dom Pedro I");
        nomeEstacoes.add("Estação tubo Érico Veríssimo");
        nomeEstacoes.add("Estação tubo Erton Coelho");
        nomeEstacoes.add("Estação tubo Eucaliptos");
        nomeEstacoes.add("Estação tubo Euclides da Cunha");
        nomeEstacoes.add("Estação tubo Fanny (Freis Carmelitas)");
        nomeEstacoes.add("Estação tubo Fernando de Noronha");
        nomeEstacoes.add("Estação tubo Ferrari");
        nomeEstacoes.add("Estação tubo Ferrovila");
        nomeEstacoes.add("Estação tubo Freis Carmelitas");
        nomeEstacoes.add("Estação tubo Gago Coutinho");
        nomeEstacoes.add("Estação tubo Gastão Câmara");
        nomeEstacoes.add("Estação tubo Germânia");
        nomeEstacoes.add("Estação tubo Getúlio Vargas");
        nomeEstacoes.add("Estação tubo Guadalupe(Conselheiro Laurindo)");
        nomeEstacoes.add("Estação tubo Guadalupe(João Negrão)");
        nomeEstacoes.add("Estação tubo Henry Ford");
        nomeEstacoes.add("Estação tubo Herculano de Araújo");
        nomeEstacoes.add("Estação tubo Hipólito da Costa");
        nomeEstacoes.add("Estação tubo Holanda");
        nomeEstacoes.add("Estação tubo Hospital Cajuru");
        nomeEstacoes.add("Estação tubo Hospital do Trabalhador");
        nomeEstacoes.add("Estação tubo Hospital Militar");
        nomeEstacoes.add("Estação tubo Imperial");
        nomeEstacoes.add("Estação tubo Itajubá");
        nomeEstacoes.add("Estação tubo Jardim Botânico");
        nomeEstacoes.add("Estação tubo Jardim Botânico");
        nomeEstacoes.add("Estação tubo Jardim das Américas");
        nomeEstacoes.add("Estação tubo João Negrão");
        nomeEstacoes.add("Estação tubo João Viana Seiler");
        nomeEstacoes.add("Estação tubo Joaquim Nabuco");
        nomeEstacoes.add("Estação tubo José Clementino");
        nomeEstacoes.add("Estação tubo Bettega");
        nomeEstacoes.add("Estação tubo Kennedy");
        nomeEstacoes.add("Estação tubo Lindoia");
        nomeEstacoes.add("Estação tubo Major Heitor Guimarães");
        nomeEstacoes.add("Estação tubo Marechal Deodoro");
        nomeEstacoes.add("Estação tubo Marechal Floriano");
        nomeEstacoes.add("Estação tubo Maria Clara (Perpétuo Socorro)");
        nomeEstacoes.add("Estação tubo Mariano Torres");
        nomeEstacoes.add("Estação tubo Marumby");
        nomeEstacoes.add("Estação tubo Mercês");
        nomeEstacoes.add("Estação tubo Morretes");
        nomeEstacoes.add("Estação tubo Mossunguê");
        nomeEstacoes.add("Estação tubo Moysés Marcondes");
        nomeEstacoes.add("Estação tubo Museu Oscar Niemeyer");
        nomeEstacoes.add("Estação tubo Nestor de Castro");
        nomeEstacoes.add("Estação tubo Nova Europa");
        nomeEstacoes.add("Estação tubo Osternack");
        nomeEstacoes.add("Estação tubo Ouro Verde");
        nomeEstacoes.add("Estação tubo Pádua Fleury");
        nomeEstacoes.add("Estação tubo Paiol");
        nomeEstacoes.add("Estação tubo Palácio Iguaçu");
        nomeEstacoes.add("Estação tubo Parolin");
        nomeEstacoes.add("Estação tubo Parque Iguaçu");
        nomeEstacoes.add("Estação tubo Passarela (São Judas Tadeu)");
        nomeEstacoes.add("Estação tubo Passeio Público");
        nomeEstacoes.add("Estação tubo Pastor Manoel Virgínio de Souza");
        nomeEstacoes.add("Estação tubo Paulo Gorski");
        nomeEstacoes.add("Estação tubo Paulo Kissula");
        nomeEstacoes.add("Estação tubo Pedro Gusso");
        nomeEstacoes.add("Estação tubo Perpétuo Socorro");
        nomeEstacoes.add("Estação tubo Petit Carneiro");
        nomeEstacoes.add("Estação tubo Praça 19 de Dezembro");
        nomeEstacoes.add("Estação tubo Praça 29 de Março");
        nomeEstacoes.add("Estação tubo Praça Carlos Gomes");
        nomeEstacoes.add("Estação tubo Praça da Bandeira");
        nomeEstacoes.add("Estação tubo Praça da Ucrânia");
        nomeEstacoes.add("Estação tubo Praça das Mercês");
        nomeEstacoes.add("Estação tubo Praça das Nações");
        nomeEstacoes.add("Estação tubo Praça do Expedicionário");
        nomeEstacoes.add("Estação tubo Praça Eufrásio Correia");
        nomeEstacoes.add("Estação tubo Praça Osório");
        nomeEstacoes.add("Estação tubo Praça Oswaldo Cruz");
        nomeEstacoes.add("Estação tubo Praça Rui Barbosa");
        nomeEstacoes.add("Estação tubo Praça Rui Barbosa");
        nomeEstacoes.add("Estação tubo Praça Seminário");
        nomeEstacoes.add("Estação tubo Praça Tiradentes");
        nomeEstacoes.add("Estação tubo Praça Tiradentes");
        nomeEstacoes.add("Estação tubo (Nestor de Castro)");
        nomeEstacoes.add("Estação tubo Prefeitura");
        nomeEstacoes.add("Estação tubo Presidente Taunay");
        nomeEstacoes.add("Estação tubo Prof. Maria Aguiar");
        nomeEstacoes.add("Estação tubo Teixeira");
        nomeEstacoes.add("Estação tubo PUC");
        nomeEstacoes.add("Estação tubo Quartel");
        nomeEstacoes.add("Estação tubo Quitandinha");
        nomeEstacoes.add("Estação tubo Rio Barigui");
        nomeEstacoes.add("Estação tubo Roberto Hauer");
        nomeEstacoes.add("Estação tubo Rodoferroviária");
        nomeEstacoes.add("Estação tubo Rodoferroviária");
        nomeEstacoes.add("Estação tubo Rosa Tortato");
        nomeEstacoes.add("Estação tubo Sagrado Coração");
        nomeEstacoes.add("Estação tubo Salgado Filho");
        nomeEstacoes.add("Estação tubo Santa Bernadethe");
        nomeEstacoes.add("Estação tubo Santa Quitéria");
        nomeEstacoes.add("Estação tubo Santa Regina");
        nomeEstacoes.add("Estação tubo São Grato");
        nomeEstacoes.add("Estação tubo São Judas Tadeu");
        nomeEstacoes.add("Estação tubo São Pedro");
        nomeEstacoes.add("Estação tubo Secretarias");
        nomeEstacoes.add("Estação tubo Sebastião Paraná");
        nomeEstacoes.add("Estação tubo Sete de Setembro");
        nomeEstacoes.add("Estação tubo Silva Jardim");
        nomeEstacoes.add("Estação tubo Teffé");
        nomeEstacoes.add("Estação tubo Templo de Curitiba");
        nomeEstacoes.add("Estação tubo Teófilo Otôni");
        nomeEstacoes.add("Estação tubo TRE");
        nomeEstacoes.add("Estação tubo Unidade de Saúde Campo Comprido (Templo de Curitiba)");
        nomeEstacoes.add("Estação tubo Urbano Lopes");
        nomeEstacoes.add("Estação tubo UTFPR");
        nomeEstacoes.add("Estação tubo Viaduto Capanema");
        nomeEstacoes.add("Estação tubo Vila Acordes");
        nomeEstacoes.add("Estação tubo Vila Fanny");
        nomeEstacoes.add("Estação tubo Vila Guaíra");
        nomeEstacoes.add("Estação tubo Vila Nova");
        nomeEstacoes.add("Estação tubo Vila São Pedro");
        nomeEstacoes.add("Estação tubo Visconde de Nácar");
        nomeEstacoes.add("Estação tubo Vital Brasil");
        nomeEstacoes.add("Estação tubo Wenceslau Braz");
        nomeEstacoes.add("Estação tubo Westphalen");
        nomeEstacoes.add("Estação tubo Winston Churchill");
        nomeEstacoes.add("Estação tubo Xapinhal");
        nomeEstacoes.add("Estação tubo Xaxim");
        nomeEstacoes.add("Estação tubo Xaxim");
        
        Coordenadas coordenadas = new Coordenadas();
         EstacaoDao dao = new EstacaoDao();
        for(int i=0; i<nomeEstacoes.size(); i++){
           estacao = new Estacao();
           estacao.setNome(nomeEstacoes.get(i));
           coordenadas.setNomeEstacao(nomeEstacoes.get(i));
           estacao.setLatitude(coordenadas.getLatitude());
           estacao.setLongitude(coordenadas.getLongitude());
           dao.saveOrUpdate(estacao);
        }
    }
}
